version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: full_app
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - myDbPostgres
    volumes:
      - api:/usr/src/app/
    networks:
      - fullstack
    environment:
      connStr: "host=myDbPostgres user=CardExamAdmin password=password dbname=CardExam port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      waitTime: "120s"

  myDbPostgres:
    image: postgres:latest
    container_name: myDb
    environment:
      POSTGRES_DB: CardExam
      POSTGRES_USER: CardExamAdmin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - myDbPostgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  api:
  myDbPostgres:


networks:
  fullstack:
    driver: bridge
